### PR TITLE
[breaking] - init v3 changes, new sdk, new wagmi, new connectors

### PR DESCRIPTION
**Pull request by jnsdls**

### CODE REVIEW

**Comment by jnsdls** [comment]
requires https://github.com/thirdweb-dev/typescript-sdk/pull/477

**Comment by jnsdls** [comment]
will fix: https://github.com/thirdweb-dev/react/issues/89, https://github.com/thirdweb-dev/react/issues/46, https://github.com/thirdweb-dev/react/issues/80

**Comment by joaquim-verges** [comment]
Feedback/walkthrough experience upgrading an existing repo (ethrone):

- `chainId` is still required in `ThirdwebProvider`
- Module '"@thirdweb-dev/react"' has no exported member 'useAddress' - guess i have to use `useAccount` from wagmi?  kinda wish we'd export that, it's so convenient for everything
- had to change the default useMetamask to useQuery format `const { connect: connectWithMetamask } = useMetamask();`

super weird error with basic useMetamask setup + useAccount for the address:
```
Warning: Text content did not match. Server: "Connect with Metamask" Client: "Disconnect"
```
looks like server vs client tried to render something diff, not sure if its our hook or wagmi's fault

**Comment by jnsdls** [comment]
> Feedback/walkthrough experience upgrading an existing repo (ethrone):
> 
> * `chainId` is still required in `ThirdwebProvider` **- solved**
> * Module '"@thirdweb-dev/react"' has no exported member 'useAddress' - guess i have to use `useAccount` from wagmi?  kinda wish we'd export that, it's so convenient for everything  **- solved**
> * had to change the default useMetamask to useQuery format `const { connect: connectWithMetamask } = useMetamask();` **- will probably stay this way**
> 
> super weird error with basic useMetamask setup + useAccount for the address:
> 
> ```
> Warning: Text content did not match. Server: "Connect with Metamask" Client: "Disconnect"
> ```
> 
> looks like server vs client tried to render something diff, not sure if its our hook or wagmi's fault **- working on it with tom**

**Pull request closed without merging**
